server:
  port: 8081
spring:
  application:
    name: micro-app-springboot
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/spring_cloud_docker?userUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: Aa123456
#      max-wait: 60000
#      min-idle: 15
#      initial-size: 15
#      validation-query: SELECT 1
#      test-on-borrow: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
logging:
  level:
    root: INFO
# keycloak config.
#keycloak:
#  realm: SpringBoot
#  auth-server-url: http://localhost:8180/auth
#  ssl-required: external
#  resource: product-app
#  public-client: true
#  verify-token-audience: true
#  use-resource-role-mappings: true
#  confidential-port: 0
#  security-constraints[0]:
#    authRoles[0]: role-p
#    securityCollections[0]:
#      patterns[0]: /
keycloak:
  realm: SpringBoot
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: product-app
  public-client: true
product:
  service:
    url: http://localhost:8081/products
